/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stockcontrol;
        
/**
 *
 * @author celik
 */
public class NewProduct extends javax.swing.JFrame {

    String ID;      //Product ID

   
    private boolean initCompleted = false; //flag for all component init completed

    ConnectionDB npConnection;      //DB reference
    
    /*
     * Check all input avoid null entry
     */
    private boolean checkNullInput() {
        if(Integer.parseInt(newProductID.getText())==0)
        {
            return false;
        }
        else if(newProductDesc.getText()==null) 
        {
            return false;
        }
        else if (newProductName.getText()==null) 
        {
            return false;
        }
        else if (Integer.parseInt(newProductCritical.getText())==0)
        {
            return false;
        }
        else if (Integer.parseInt(newProductStockLevel.getText())==0)
        {
            return false;
        }
        else if (newProductPrice.getText()==null)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * Creates new form NewProduct
     */
    public NewProduct() {
        
        npConnection = new ConnectionDB();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftLayout3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        newProductDesc = new javax.swing.JTextField();
        newProductName = new javax.swing.JTextField();
        newProductStockLevel = new javax.swing.JTextField();
        newProductCritical = new javax.swing.JTextField();
        newProductPrice = new javax.swing.JTextField();
        newProductID = new javax.swing.JTextField();
        newProductSE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftLayout3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Product ID");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Name");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Descripton");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Stock Level");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Critical Level");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Price per Unit ");

        newProductDesc.setText("0");
        newProductDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductDescActionPerformed(evt);
            }
        });

        newProductName.setText("0");
        newProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameActionPerformed(evt);
            }
        });

        newProductStockLevel.setText("0");
        newProductStockLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductStockLevelActionPerformed(evt);
            }
        });
        newProductStockLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newProductStockLevelKeyTyped(evt);
            }
        });

        newProductCritical.setText("0");
        newProductCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductCriticalActionPerformed(evt);
            }
        });
        newProductCritical.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newProductCriticalKeyTyped(evt);
            }
        });

        newProductPrice.setText("0");
        newProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductPriceActionPerformed(evt);
            }
        });
        newProductPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newProductPriceKeyTyped(evt);
            }
        });

        newProductID.setText("0");
        newProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductIDActionPerformed(evt);
            }
        });
        newProductID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newProductIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout leftLayout3Layout = new javax.swing.GroupLayout(leftLayout3);
        leftLayout3.setLayout(leftLayout3Layout);
        leftLayout3Layout.setHorizontalGroup(
            leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newProductDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductCritical, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        leftLayout3Layout.setVerticalGroup(
            leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductCritical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(leftLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel1.add(leftLayout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 290));

        newProductSE.setText("Save and Exit");
        newProductSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductSEActionPerformed(evt);
            }
        });
        jPanel1.add(newProductSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProductDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductDescActionPerformed

    private void newProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameActionPerformed

    private void newProductStockLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductStockLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductStockLevelActionPerformed

    private void newProductCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductCriticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductCriticalActionPerformed

    private void newProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceActionPerformed

    private void newProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductIDActionPerformed

    private void newProductSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductSEActionPerformed
        // TODO add your handling code here:
        String ID, name, description, stockLevel, criticLevel, price; //product specification
        String[] sqlParams = new String[6];
        
        if(checkNullInput()) // check inputs are not null
        {  
           ID = newProductID.getText();
           name = newProductName.getText();
           description = newProductDesc.getText();
           stockLevel = newProductStockLevel.getText();
           criticLevel = newProductCritical.getText();
           price = newProductPrice.getText();
           sqlParams[0] = ID;               //ID
           sqlParams[1] = name;             //NAME
           sqlParams[2] = description;      //DESCRIPTION
           sqlParams[3] = stockLevel;       //STOCK LEVEL
           sqlParams[4] = criticLevel;      //CRITICAL LEVEL
           sqlParams[5] = price;            //PRICE
           
           npConnection.addNewProduct(sqlParams);
           this.dispose();
           
           
        }
    }//GEN-LAST:event_newProductSEActionPerformed

    private void newProductIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newProductIDKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();        

        if(!Character.isDigit(c)) { //for get only numeric input
            evt.consume();
        }
    }//GEN-LAST:event_newProductIDKeyTyped

    private void newProductStockLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newProductStockLevelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();        

        if(!Character.isDigit(c)) { //for get only numeric input
            evt.consume();
        }
    }//GEN-LAST:event_newProductStockLevelKeyTyped

    private void newProductCriticalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newProductCriticalKeyTyped
        // TODO add your handling code here:
       /*
        char c = evt.getKeyChar();        

        if(!Character.isDigit(c)) { //for get only numeric input
            evt.consume();
        }*/
    }//GEN-LAST:event_newProductCriticalKeyTyped

    private void newProductPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newProductPriceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();        

        if(!Character.isDigit(c)) { //for get only numeric input
            evt.consume();
        }
    }//GEN-LAST:event_newProductPriceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftLayout3;
    private javax.swing.JTextField newProductCritical;
    private javax.swing.JTextField newProductDesc;
    private javax.swing.JTextField newProductID;
    private javax.swing.JTextField newProductName;
    private javax.swing.JTextField newProductPrice;
    private javax.swing.JButton newProductSE;
    private javax.swing.JTextField newProductStockLevel;
    // End of variables declaration//GEN-END:variables
}
